### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by isinteger** [ClearURLs/Addon#137] opened 2021-08-11 13:23 UTC
How to add site on whitelist?

**Comment by axonasif** [comment] 2021-08-18 14:48
I'm on the same boat, wish if there was an option.

**Comment by Gwouigwoui** [comment] 2021-12-13 23:23
I concur. Same problem with Pocket in webmails : instead of saving the articles it opens them in a new tab. Whitelisting would make the extension even more amazing!

**Comment by laurent-simon** [comment] 2022-01-26 18:50
Allowing to disable ClearURLs on some sites is a must-have. Some sites that display images from others (not for tracking purpose) are unusable without this feature.

Actually, on this kind of sites, without this, you need to completely disable the ClearURLs extension.

**Comment by posita** [comment] 2022-05-15 15:15
Duplicate of #93 (which predates this by 7 mos)?

**Comment by inson1** [comment] 2023-12-15 14:46
@isinteger please close it

**Closed** 2023-12-15 17:40 UTC
