### ISSUE TITLE
Performing Actions in Gmail with Extension Enabled Cases No Other Websites to Work in Brave

### ISSUE THREAD

**Issue by feerlessleadr** [ClearURLs/Addon#187] opened 2022-03-25 17:27 UTC
As the title states, I noted starting yesterday that anytime I would do anything in Gmail (send an email, look in drafts folder, schedule an email to send, etc.), after a period of maybe 30 seconds to 2 minutes, the internet for just Brave would no longer work. Anytime I tried to navigate to another website (either in the same tab or a new tab), it would just spin endlessly. I confirmed that the internet was working on my laptop, as I have to use Edge for work, and while the internet was not working in Brave (tried many sites), it continued to work in Edge (using the same sites).

The only way to fix this was to clear my browsing data ("Cookies and other side data" & "Cached images and files") and then restart brave. After the restart, the internet would begin working in Brave once again. This same issue was happening on my work laptop, my personal surface, as well as my Windows server (all running Windows 10 Pro).

I had assumed this was a Brave issue, since it was just updated, but when I created a fresh Brave profile, the issue did not persist. I then started adding in back my extensions one by one, and luckily for me, ClearURLs was the 4th one I added. As soon as the extension was added and I tried to do something in Gmail, the issue began again, and as soon as I disabled the extension, all of the websites that were just spinning without loading, loaded immediately. 

[Here is a link](https://github.com/brave/brave-browser/issues/21884) to the Brave Github where I initially reported this, as I'm not sure if this is a Brave issue or an extension issue. 

Thanks

**Comment by KevinRoebert** [comment] 2022-03-25 17:29
Duplicate of #185 and #186

**Closed by KevinRoebert** 2022-03-25 17:29 UTC
